'use client';
import {useEffect,useState} from 'react';
import {Send,ArrowLeft,ShieldCheck} from 'lucide-react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {createClient} from '@/lib/supabase/client';
export default function Chat(){const p=useSearchParams();const supabase=createClient();const initialConversation=p.get('conversation')||'';const listingId=p.get('listingId')||'';const [conversationId,setConversationId]=useState(initialConversation),[listing,setListing]=useState<any>(null),[msgs,setMsgs]=useState<any[]>([]),[text,setText]=useState(''),[userId,setUserId]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{try{const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href=`/login?next=${encodeURIComponent(window.location.pathname+window.location.search)}`;return}setUserId(user.id);let cid=conversationId;if(!cid&&listingId){const r=await fetch('/api/conversations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({listing_id:listingId})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Percakapan gagal dibuka.');cid=j.data.id;setConversationId(cid)}if(!cid){throw new Error('Percakapan tidak ditemukan.')}const r=await fetch(`/api/messages?conversation_id=${encodeURIComponent(cid)}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Pesan gagal dimuat.');setMsgs(j.data||[]);const c=await fetch('/api/conversations',{cache:'no-store'});if(c.ok){const cj=await c.json();const current=(cj.data||[]).find((x:any)=>x.id===cid);if(current)setListing(current.listings)}}catch(e){setError(e instanceof Error?e.message:'Chat gagal dimuat.')}finally{setLoading(false)}};
 useEffect(()=>{load();const t=setInterval(()=>{if(conversationId)fetch(`/api/messages?conversation_id=${encodeURIComponent(conversationId)}`,{cache:'no-store'}).then(r=>r.ok?r.json():null).then(j=>j&&setMsgs(j.data||[])).catch(()=>{})},5000);return()=>clearInterval(t)},[conversationId,listingId]);
 const send=async()=>{if(!text.trim()||!conversationId)return;const body=text.trim();setText('');const r=await fetch('/api/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({conversation_id:conversationId,body})});const j=await r.json();if(!r.ok){setError(j.error||'Pesan gagal dikirim.');setText(body);return}setMsgs(v=>[...v,j.data])};
 return <main className="container py-8 max-w-3xl"><Link href="/" className="text-sm text-gray-500 flex items-center gap-2"><ArrowLeft className="w-4 h-4"/>Kembali</Link><div className="card mt-5 overflow-hidden"><div className="p-5 border-b"><div className="flex items-center gap-2"><b>Chat Lumagada</b><ShieldCheck className="w-4 h-4 text-green-600"/></div><div className="text-xs text-green-600 mt-1">{listing?.title||'Percakapan marketplace'}</div></div>{error&&<div className="p-3 bg-red-50 text-red-700 text-sm border-b">{error}</div>}<div className="h-[430px] p-5 space-y-3 bg-[#f7faf8] overflow-y-auto">{loading?<p className="text-center text-gray-400">Memuat percakapan…</p>:msgs.length===0?<p className="text-center text-gray-400 text-sm">Belum ada pesan. Mulai percakapan.</p>:msgs.map((m:any)=><div key={m.id} className={`max-w-[75%] p-3 rounded-2xl text-sm ${m.sender_id===userId?'bg-green-600 text-white ml-auto':'bg-white border'}`}>{m.body}</div>)}</div><div className="p-3 border-t flex gap-2"><input className="input" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="Tulis pesan..." maxLength={4000}/><button className="btn btn-primary" onClick={send} disabled={!text.trim()||loading}><Send className="w-4 h-4"/></button></div></div></main>}
