'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {Search,MapPin,ShieldCheck,Truck,MessageCircle,Navigation,SlidersHorizontal,PlayCircle,LocateFixed} from 'lucide-react';
import {categories,listings} from '@/lib/data';
import {ListingCard} from '@/components/listing-card';

const cities:Record<string,{lat:number;lng:number}>={Indonesia:{lat:-2.5489,lng:118.0149},Jakarta:{lat:-6.2088,lng:106.8456},Bandung:{lat:-6.9175,lng:107.6191},Surabaya:{lat:-7.2575,lng:112.7521},Yogyakarta:{lat:-7.7956,lng:110.3695},Tangerang:{lat:-6.1783,lng:106.6319}};
const categoryImages:Record<string,string>={mobil:'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=320&q=85',motor:'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=320&q=85',properti:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=320&q=85',elektronik:'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=320&q=85',jasa:'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=320&q=85',fashion:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=320&q=85',rumah:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=320&q=85',hobi:'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=320&q=85',hewan:'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=320&q=85',buku:'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=320&q=85',bisnis:'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=320&q=85',lainnya:'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=320&q=85'};
const distanceKm=(a:number,b:number,c:number,d:number)=>{const R=6371,rad=Math.PI/180,x=(c-a)*rad,y=(d-b)*rad,h=Math.sin(x/2)**2+Math.cos(a*rad)*Math.cos(c*rad)*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))};

export default function Home(){
 const [q,setQ]=useState(''),[category,setCategory]=useState(''),[loc,setLoc]=useState('Jakarta'),[radius,setRadius]=useState('Semua jarak'),[coords,setCoords]=useState(cities.Jakarta),[usingGps,setUsingGps]=useState(false),[locating,setLocating]=useState(true),[gpsError,setGpsError]=useState(''),[extra,setExtra]=useState<any[]>([]),[submitted,setSubmitted]=useState({q:'',category:''});
 useEffect(()=>{const p=new URLSearchParams(location.search);const initialQ=p.get('q')||'';const initialCategory=p.get('category')||'';setQ(initialQ);setCategory(initialCategory);setSubmitted({q:initialQ,category:initialCategory});try{setExtra(JSON.parse(localStorage.getItem('lumagada-listings')||'[]'))}catch{setExtra([])} const saved=localStorage.getItem('lumagada-location');if(saved){try{const v=JSON.parse(saved);if(v?.lat&&v?.lng){setCoords({lat:v.lat,lng:v.lng});setUsingGps(true);setLoc('Lokasi saya');setLocating(false);return}}catch{}} if(navigator.geolocation){navigator.geolocation.getCurrentPosition(pos=>{const next={lat:pos.coords.latitude,lng:pos.coords.longitude};setCoords(next);setUsingGps(true);setLoc('Lokasi saya');setLocating(false);localStorage.setItem('lumagada-location',JSON.stringify(next))},()=>setLocating(false),{enableHighAccuracy:true,maximumAge:300000,timeout:10000})}else setLocating(false)},[]);
 const useMyLocation=()=>{setGpsError('');setLocating(true);if(!navigator.geolocation){setGpsError('Lokasi tidak tersedia di browser ini.');setLocating(false);return}navigator.geolocation.getCurrentPosition(pos=>{const next={lat:pos.coords.latitude,lng:pos.coords.longitude};setCoords(next);setUsingGps(true);setLoc('Lokasi saya');setLocating(false);localStorage.setItem('lumagada-location',JSON.stringify(next))},()=>{setGpsError('Izin lokasi ditolak. Pilih kota secara manual atau izinkan lokasi di browser.');setLocating(false)},{enableHighAccuracy:true,maximumAge:300000,timeout:10000})};
 const runSearch=()=>{setSubmitted({q:q.trim(),category});const u=new URL(window.location.href);if(q.trim())u.searchParams.set('q',q.trim());else u.searchParams.delete('q');if(category)u.searchParams.set('category',category);else u.searchParams.delete('category');window.history.replaceState({},'',u.toString())};
 const all=[...extra,...listings];const selectedCategory=submitted.category?categories.find(c=>c[2]===submitted.category)?.[1]||submitted.category:'';const filtered=useMemo(()=>all.map(x=>({...x,distance:distanceKm(coords.lat,coords.lng,x.lat,x.lng)})).filter(x=>{const text=(x.title+' '+x.category+' '+x.location).toLowerCase(),term=submitted.q.toLowerCase();const matchesKeyword=!term||text.includes(term);const matchesCategory=!submitted.category||x.category.toLowerCase()===selectedCategory.toLowerCase()||(submitted.category==='jasa'&&x.category==='Jasa & Lowongan');const limit=radius==='Semua jarak'?Infinity:Number(radius);return matchesKeyword&&matchesCategory&&x.distance<=limit}).sort((a,b)=>a.distance-b.distance),[all,submitted,selectedCategory,coords,radius]);
 return <main>
  <div className="bg-[#15251d] text-white"><div className="container py-2.5 flex items-center justify-center gap-2 text-xs md:text-sm font-semibold text-center"><PlayCircle className="w-4 h-4 shrink-0 text-green-300"/><span>Ingin iklan tetap tayang? Klik iklan sponsor dan tonton selama 30 detik untuk mendapatkan <b className="text-green-300">+1 hari</b> masa tayang.</span><Link href="/dashboard" className="hidden sm:inline underline underline-offset-2 text-green-300">Kelola iklan</Link></div></div>
  <section className="bg-white border-b border-red-100"><div className="container pt-6 md:pt-8">
   <div className="relative isolate overflow-hidden rounded-[28px] min-h-[270px] md:min-h-[350px] bg-gradient-to-br from-[#86000e] via-[#d6081b] to-[#ff8a91] text-white shadow-[0_18px_50px_rgba(123,0,15,.24)]">
    <div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_18%,rgba(255,255,255,.42),transparent_22%),radial-gradient(circle_at_96%_76%,rgba(255,255,255,.18),transparent_28%)]"/>
    <svg className="absolute inset-0 w-full h-full opacity-30" viewBox="0 0 1200 360" preserveAspectRatio="none" aria-hidden="true"><g fill="#5b0009"><rect x="0" y="240" width="85" height="120"/><rect x="72" y="205" width="68" height="155"/><rect x="132" y="255" width="110" height="105"/><rect x="226" y="180" width="75" height="180"/><rect x="295" y="225" width="110" height="135"/><rect x="396" y="160" width="92" height="200"/><rect x="475" y="218" width="125" height="142"/><rect x="584" y="190" width="82" height="170"/><rect x="655" y="245" width="95" height="115"/><rect x="736" y="145" width="92" height="215"/><rect x="820" y="215" width="120" height="145"/><rect x="926" y="175" width="86" height="185"/><rect x="1004" y="235" width="95" height="125"/><rect x="1088" y="125" width="112" height="235"/></g><g stroke="#fff" strokeWidth="3" fill="none" opacity=".65"><path d="M615 310h28l-8-92h-12z"/><path d="M623 218l6-34 6 34"/><circle cx="629" cy="181" r="3" fill="#fff"/></g></svg>
    <div className="relative z-10 grid md:grid-cols-[1.15fr_.85fr] items-center gap-6 px-7 py-8 md:px-12 md:py-10 min-h-[270px] md:min-h-[350px]">
      <div className="max-w-2xl">
       <div className="text-[11px] md:text-xs font-black tracking-[.24em] uppercase text-white/75">Marketplace Indonesia</div>
       <h1 className="text-[42px] md:text-[64px] font-black tracking-[-.045em] leading-[.96] mt-3">LU MAU GUE ADA</h1>
       <p className="text-white/90 mt-4 text-base md:text-xl max-w-xl leading-relaxed">Temukan apa pun di sekitar kamu.<br className="hidden md:block"/> Lebih dekat, lebih mudah, lebih nyata.</p>
       <div className="mt-6 flex flex-wrap gap-2.5 text-xs md:text-sm font-bold">
        <span className="inline-flex items-center gap-2 rounded-full bg-white/12 border border-white/20 px-3.5 py-2"><span className="w-6 h-6 rounded-full bg-white text-[#d6081b] inline-flex items-center justify-center text-[12px]">●</span>Lokal & Terdekat</span>
        <span className="inline-flex items-center gap-2 rounded-full bg-white/12 border border-white/20 px-3.5 py-2"><span className="w-6 h-6 rounded-full bg-white text-[#d6081b] inline-flex items-center justify-center text-[12px]">✓</span>Aman & Terpercaya</span>
        <span className="inline-flex items-center gap-2 rounded-full bg-white/12 border border-white/20 px-3.5 py-2"><span className="w-6 h-6 rounded-full bg-white text-[#d6081b] inline-flex items-center justify-center text-[12px]">↯</span>Cepat & Mudah</span>
       </div>
      </div>
      <div className="flex justify-center md:justify-end items-center">
       <div className="relative w-[250px] md:w-[370px] lg:w-[410px]">
        <div className="absolute -inset-10 rounded-full bg-white/25 blur-3xl"/>
        <img src="/lumagada-logo.svg" alt="Lumagada — Lu Mau Gue Ada" className="relative w-full h-auto object-contain drop-shadow-[0_14px_18px_rgba(70,0,0,.25)]"/>
       </div>
      </div>
    </div>
    <div className="absolute left-1/2 bottom-3 -translate-x-1/2 flex items-center gap-1.5"><span className="w-8 h-1.5 rounded-full bg-white"/><span className="w-8 h-1.5 rounded-full bg-white/35"/><span className="w-8 h-1.5 rounded-full bg-white/35"/></div>
   </div>
   <div className="max-w-5xl mx-auto -mt-8 relative z-20 px-2 pb-8"><form onSubmit={e=>{e.preventDefault();runSearch()}} className="card shadow-xl p-2 flex flex-col md:flex-row gap-2 bg-white"><div className="search-field flex-1"><Search className="search-icon text-gray-400"/><input aria-label="Cari di Lumagada" className="input search-input" value={q} onChange={e=>{setQ(e.target.value);setCategory('')}} placeholder="Cari mobil, HP, rumah, jasa..."/></div><div className="location-field md:w-48"><MapPin className="search-icon text-gray-400"/><select aria-label="Pilih lokasi" className="input search-location-input appearance-none" value={usingGps?'Lokasi saya':loc} onChange={e=>{const v=e.target.value;setUsingGps(false);setLoc(v);setCoords(cities[v])}}><option>Jakarta</option><option>Bandung</option><option>Surabaya</option><option>Yogyakarta</option><option>Tangerang</option><option>Indonesia</option>{usingGps&&<option>Lokasi saya</option>}</select></div><button type="button" onClick={useMyLocation} className="btn btn-light whitespace-nowrap" disabled={locating}><LocateFixed className="button-icon w-4 h-4"/>{locating?'Mendeteksi...':'Lokasi saya'}</button><button type="submit" className="btn btn-primary md:px-8"><Search className="button-icon w-4 h-4"/>Cari</button></form><div className="mt-3 flex flex-wrap items-center justify-center gap-2"><span className="text-sm font-bold text-gray-700 flex items-center gap-1"><SlidersHorizontal className="w-4 h-4"/>Radius:</span>{['Semua jarak','5','10','25','50'].map(r=><button key={r} type="button" onClick={()=>setRadius(r)} className={`px-3 py-1.5 rounded-full text-xs font-bold border transition ${radius===r?'bg-green-600 text-white border-green-600':'bg-white text-gray-600 border-gray-200 hover:border-green-300'}`}>{r==='Semua jarak'?'Semua jarak':`≤ ${r} km`}</button>)}</div>{gpsError&&<p className="text-xs text-red-600 mt-2 text-center">{gpsError}</p>}{usingGps&&<p className="text-xs text-green-700 mt-2 flex items-center justify-center gap-1"><Navigation className="w-3 h-3"/>Jarak dihitung dari lokasi kamu saat ini.</p>}</div>
  </div></section>
  <section className="container py-10"><h2 className="text-2xl font-black">Kategori</h2><p className="text-gray-500 text-sm mt-1">Pilih kategori untuk langsung melihat iklan yang sesuai.</p><div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-6 lg:grid-cols-12 gap-4 mt-6">{categories.map(([,name,slug])=>{const image=categoryImages[slug]||categoryImages.lainnya;return <button type="button" onClick={()=>{setCategory(slug);setQ('');setSubmitted({q:'',category:slug});const u=new URL(window.location.href);u.searchParams.delete('q');u.searchParams.set('category',slug);window.history.replaceState({},'',u.toString())}} key={slug} className={`group flex flex-col items-center text-center hover:-translate-y-1 transition ${submitted.category===slug?'scale-[1.02]':''}`}><div className={`w-full aspect-square max-w-[92px] mx-auto overflow-hidden rounded-[22px] bg-[#fff3f4] border border-[#f6dddd] shadow-sm group-hover:shadow-md group-hover:border-red-200 transition ${submitted.category===slug?'ring-2 ring-red-400 ring-offset-2':''}`}><img src={image} alt={name} className="w-full h-full object-cover" loading="lazy"/></div><div className="text-xs md:text-sm font-bold mt-3 leading-tight max-w-[95px]">{name}</div></button>})}</div></section>
  <section className="container pb-8"><div className="flex items-end justify-between gap-4"><div><h2 className="text-2xl font-black">{selectedCategory?`Iklan ${selectedCategory}`:submitted.q?`Hasil pencarian “${submitted.q}”`:'Iklan di sekitar kamu'}</h2><p className="text-gray-500 text-sm mt-1">{selectedCategory?`Menampilkan iklan dalam kategori ${selectedCategory}, diurutkan dari yang paling dekat.`:submitted.q?'Hasil ditampilkan sesuai kata kunci, lokasi, dan radius yang dipilih.':'Diurutkan berdasarkan jarak dari lokasi kamu.'}</p></div><span className="text-sm font-bold text-green-700 whitespace-nowrap">{filtered.length} iklan</span></div><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 mt-6">{filtered.map(x=><ListingCard item={x} key={x.id}/>)}</div>{filtered.length===0&&<div className="card p-10 text-center mt-6"><b>Tidak ada iklan yang cocok.</b><p className="text-sm text-gray-500 mt-1">Coba kata kunci lain, kategori lain, hapus radius, atau perluas area pencarian.</p></div>}</section>
  <section className="container pb-12"><div className="card p-6 md:p-8 bg-white"><div className="grid md:grid-cols-3 gap-6"><div><b className="text-lg">Lokasi otomatis</b><p className="text-gray-500 text-sm mt-1">Lumagada meminta izin lokasi untuk menghitung jarak iklan dari posisi kamu secara otomatis.</p></div><div><b className="text-lg">Iklan gratis 14 hari</b><p className="text-gray-500 text-sm mt-1">Pasang iklan tanpa ribet. Setelah 14 hari, login dan re-up dari akun untuk tayang lagi.</p></div><div><b className="text-lg">+1 hari dengan iklan sponsor</b><p className="text-gray-500 text-sm mt-1">Klik iklan sponsor yang tersedia dan tonton selama 30 detik penuh untuk mendapatkan tambahan 1 hari masa tayang.</p></div></div></div></section>
  <section className="bg-[#15251d] text-white mt-2"><div className="container py-12 grid md:grid-cols-3 gap-8"><div className="flex gap-4"><ShieldCheck/><div><b>Transaksi lebih aman</b><p className="text-white/60 text-sm mt-1">Profil seller dan panduan keamanan membantu transaksi lebih nyaman.</p></div></div><div className="flex gap-4"><Truck/><div><b>COD & pengiriman</b><p className="text-white/60 text-sm mt-1">Pilih metode transaksi yang sesuai kebutuhan.</p></div></div><div className="flex gap-4"><MessageCircle/><div><b>Chat penjual</b><p className="text-white/60 text-sm mt-1">Tanya detail sebelum membuat keputusan.</p></div></div></div></section>
 </main>
}
