'use client';
import {useState} from 'react';import Link from 'next/link';import {Mail,Lock,UserRound,Phone,ShieldCheck,X} from 'lucide-react';

export default function Login(){
 const [mode,setMode]=useState<'login'|'signup'>('login');
 const [terms,setTerms]=useState(false); const [showTerms,setShowTerms]=useState(false);
 return <main className="min-h-[70vh] flex items-center justify-center px-4 py-10"><div className="card p-7 w-full max-w-md shadow">
  <div className="text-center"><div className="text-3xl font-black text-green-600">lumagada.</div><h1 className="text-2xl font-black mt-6">{mode==='login'?'Selamat datang kembali':'Buat akun Lumagada'}</h1><p className="text-gray-500 text-sm mt-2">{mode==='login'?'Masuk untuk mengelola iklan dan favorit.':'Buat akun untuk jual, beli, chat, dan mengelola iklan.'}</p></div>
  <form className="mt-7 space-y-4" onSubmit={e=>{e.preventDefault();if(mode==='signup'&&!terms)return;location.href='/dashboard'}}>
   {mode==='signup'&&<><div className="relative"><UserRound className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none"/><input className="input pl-12" type="text" placeholder="Nama lengkap" required/></div><div className="relative"><Phone className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none"/><input className="input pl-12" type="tel" placeholder="Nomor HP" required/></div></>}
   <div className="relative"><Mail className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none"/><input className="input pl-12" type="email" placeholder="Email" required/></div>
   <div className="relative"><Lock className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none"/><input className="input pl-12" type="password" placeholder="Password" required/></div>
   {mode==='signup'&&<div className="flex items-start gap-3 rounded-xl bg-[#f6f9f7] p-3 text-xs text-gray-600"><input id="terms" type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)} className="mt-0.5 h-4 w-4 accent-green-600" required/><label htmlFor="terms">Saya telah membaca dan menyetujui <button type="button" onClick={()=>setShowTerms(true)} className="font-bold text-green-700 underline underline-offset-2">Terms of Service & Agreement</button> Lumagada.</label></div>}
   <button disabled={mode==='signup'&&!terms} className="btn btn-primary w-full disabled:opacity-50 disabled:cursor-not-allowed">{mode==='login'?'Masuk':'Daftar'}</button>
  </form>
  <button className="w-full text-sm text-green-700 font-bold mt-5" onClick={()=>{setMode(mode==='login'?'signup':'login');setTerms(false)}}>{mode==='login'?'Belum punya akun? Daftar':'Sudah punya akun? Masuk'}</button><Link href="/" className="block text-center text-xs text-gray-400 mt-5">Kembali ke Lumagada</Link>
 </div>
 {showTerms&&<div className="fixed inset-0 z-50 bg-black/50 p-4 flex items-center justify-center" role="dialog" aria-modal="true"><div className="bg-white rounded-2xl w-full max-w-2xl max-h-[85vh] overflow-hidden shadow-2xl"><div className="p-5 border-b flex items-center justify-between"><div><h2 className="text-xl font-black">Terms of Service & Agreement</h2><p className="text-xs text-gray-500 mt-1">Ketentuan penggunaan Lumagada</p></div><button type="button" onClick={()=>setShowTerms(false)} className="btn p-2"><X className="w-5 h-5"/></button></div><div className="p-6 overflow-y-auto max-h-[65vh] space-y-5 text-sm text-gray-600 leading-6">
  <section><h3 className="font-black text-gray-900">1. Persetujuan</h3><p>Dengan membuat akun atau menggunakan Lumagada, pengguna menyatakan telah membaca, memahami, dan menyetujui ketentuan ini. Ketentuan dapat diperbarui untuk kebutuhan operasional, keamanan, atau perubahan peraturan yang berlaku.</p></section>
  <section><h3 className="font-black text-gray-900">2. Akun Pengguna</h3><p>Pengguna wajib memberikan informasi yang benar, lengkap, dan dapat dipertanggungjawabkan. Akun tidak boleh digunakan oleh pihak lain tanpa izin. Pengguna bertanggung jawab menjaga keamanan email, kata sandi, dan informasi akun.</p></section>
  <section><h3 className="font-black text-gray-900">3. Iklan & Konten</h3><p>Pengguna hanya boleh memasang iklan untuk barang, jasa, atau kesempatan yang benar-benar ditawarkan. Informasi, harga, kondisi, foto, dan keterangan harus akurat serta tidak menyesatkan. Lumagada berhak menolak, menyembunyikan, menghapus, atau membatasi iklan yang melanggar ketentuan.</p></section>
  <section><h3 className="font-black text-gray-900">4. Masa Tayang Iklan</h3><p>Iklan reguler berlaku selama 7 hari sejak diterbitkan. Setelah berakhir, pengguna dapat login ke akun dan melakukan re-up agar iklan dapat ditayangkan kembali. Ketentuan masa tayang dapat berbeda untuk akun atau layanan Pro sesuai kebijakan platform.</p></section>
  <section><h3 className="font-black text-gray-900">5. Barang & Aktivitas Terlarang</h3><p>Dilarang menggunakan Lumagada untuk penipuan, pemalsuan, pencucian uang, perjudian, barang ilegal, senjata, narkotika, barang curian, konten seksual ilegal, pelanggaran hak kekayaan intelektual, atau barang dan jasa lain yang dilarang oleh hukum yang berlaku di Indonesia.</p></section>
  <section><h3 className="font-black text-gray-900">6. Transaksi & Biaya Platform</h3><p>Lumagada merupakan platform yang mempertemukan pembeli dan penjual. Pengguna bertanggung jawab memastikan detail transaksi, pembayaran, pengiriman, dan serah terima. <b className="text-gray-900">Untuk transaksi dengan nilai di atas Rp1.000.000, dapat dikenakan biaya layanan platform sesuai ketentuan Lumagada yang berlaku.</b> Besaran dan mekanisme biaya dapat ditetapkan atau diperbarui oleh Lumagada dan akan diinformasikan melalui sarana resmi platform.</p></section>
  <section><h3 className="font-black text-gray-900">7. Keamanan</h3><p>Pengguna dianjurkan menggunakan chat Lumagada, melakukan verifikasi informasi, dan bertemu di tempat aman bila melakukan transaksi langsung. Jangan memberikan kata sandi, kode OTP, atau data sensitif kepada pihak lain.</p></section>
  <section><h3 className="font-black text-gray-900">8. Privasi</h3><p>Lumagada dapat mengumpulkan dan menggunakan informasi yang diperlukan untuk menyediakan layanan, keamanan akun, pencegahan penipuan, komunikasi layanan, dan pemrosesan transaksi. Pengelolaan data pribadi akan mengikuti kebijakan privasi dan hukum yang berlaku.</p></section>
  <section><h3 className="font-black text-gray-900">9. Pembatasan & Penghentian</h3><p>Lumagada dapat membatasi, menangguhkan, atau menonaktifkan akun maupun iklan apabila terdapat indikasi pelanggaran, aktivitas mencurigakan, penyalahgunaan, atau kewajiban hukum.</p></section>
  <section><h3 className="font-black text-gray-900">10. Tanggung Jawab Pengguna</h3><p>Pengguna bertanggung jawab atas isi iklan, komunikasi, dan transaksi yang dilakukan. Lumagada tidak menjamin kualitas, keaslian, kepemilikan, atau keamanan setiap barang dan jasa yang ditawarkan oleh pengguna.</p></section>
  <div className="rounded-xl bg-[#edf8ef] p-4 flex gap-3"><ShieldCheck className="w-5 h-5 text-green-600 shrink-0 mt-0.5"/><p className="text-xs">Dengan mencentang persetujuan saat pendaftaran, pengguna menyatakan setuju untuk terikat pada Terms of Service & Agreement ini serta aturan iklan dan kebijakan platform Lumagada.</p></div>
 </div><div className="p-4 border-t"><button type="button" onClick={()=>{setTerms(true);setShowTerms(false)}} className="btn btn-primary w-full">Saya Mengerti & Setuju</button></div></div></div>}
 </main>
}