'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {PlusCircle,Package,Clock,ShieldCheck,PlayCircle,Tag,LogOut,RefreshCw} from 'lucide-react';
import {createClient} from '@/lib/supabase/client';
import {rupiah} from '@/lib/data';
export default function Dashboard(){
 const supabase=createClient();const [user,setUser]=useState<any>(null),[profile,setProfile]=useState<any>(null),[items,setItems]=useState<any[]>([]),[offers,setOffers]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');const {data:{user:u}}=await supabase.auth.getUser();if(!u){window.location.href='/login?next=/dashboard';return}setUser(u);const [{data:p},{data:l,error:le}]=await Promise.all([supabase.from('profiles').select('display_name,phone,city,seller_type,seller_verified,seller_business_name').eq('id',u.id).maybeSingle(),supabase.from('listings').select('id,title,price,condition,city,status,expires_at,is_pro_listing,accepts_offers,created_at,listing_images(url,sort_order)').eq('seller_id',u.id).order('created_at',{ascending:false}).limit(100)]);if(le)setError(le.message);setProfile(p);setItems((l||[]).map((x:any)=>({...x,image:x.listing_images?.slice?.().sort((a:any,b:any)=>a.sort_order-b.sort_order)[0]?.url})));const or=await fetch('/api/offers?side=seller',{cache:'no-store'});if(or.ok){const j=await or.json();setOffers(j.data||[])}setLoading(false)};
 useEffect(()=>{load()},[]);const reup=async(id:string)=>{setBusy(id);setError('');try{const r=await fetch(`/api/listings/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reup'})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Re-up gagal.');await load()}catch(e){setError(e instanceof Error?e.message:'Re-up gagal.')}finally{setBusy('')}};const signOut=async()=>{await supabase.auth.signOut();window.location.href='/'};
 const active=items.filter(x=>x.status==='active').length,expired=items.filter(x=>x.status==='expired').length,pending=offers.filter(x=>x.status==='pending').length;
 return <main className="container py-10"><div className="flex flex-wrap justify-between items-end gap-4"><div><p className="text-gray-500">{profile?.display_name||user?.email||'Akun Lumagada'}</p><h1 className="text-3xl font-black">Dashboard Saya</h1><p className="text-gray-500 text-sm mt-2">Kelola iklan, penawaran, dan masa tayang dari satu tempat.</p></div><div className="flex gap-2"><button type="button" onClick={signOut} className="btn border"><LogOut className="w-4 h-4"/>Keluar</button><Link href="/sell" className="btn btn-primary"><PlusCircle className="w-4 h-4"/>Jual barang</Link></div></div>
 <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-7">{[['Iklan aktif',active,Package],['Iklan berakhir',expired,Clock],['Penawaran masuk',pending,Tag],['Favorit','—',Tag]].map(([a,b,I])=><div className="card p-5" key={String(a)}><I className="w-5 h-5 text-green-600"/><p className="text-sm text-gray-500 mt-4">{String(a)}</p><b className="text-2xl">{String(b)}</b></div>)}</div>
 <div className="card mt-7 p-5 bg-[#edf8ef] border-green-100 flex gap-3"><Clock className="text-green-700 shrink-0"/><div><b>Aturan iklan reguler: 14 hari</b><p className="text-sm text-gray-600 mt-1">Iklan reguler berakhir setelah 14 hari. Setelah itu lakukan re-up dari akun untuk menayangkannya kembali. Iklan Pro tidak mengikuti masa tayang reguler.</p></div></div>
 <div className="card mt-4 p-5 bg-[#15251d] text-white flex gap-3"><PlayCircle className="text-green-300 shrink-0"/><div><b>Bonus +1 hari dari iklan sponsor</b><p className="text-sm text-white/70 mt-1">Jika program sponsor tersedia, tonton iklan sponsor selama 30 detik penuh untuk mendapatkan tambahan 1 hari masa tayang sesuai ketentuan.</p></div></div>
 {error&&<div className="card mt-4 p-4 border-red-200 bg-red-50 text-sm text-red-700">{error}</div>}
 <div className="card mt-7 overflow-hidden"><div className="p-5 border-b font-black">Iklan saya</div>{loading?<div className="p-8 text-center text-gray-500">Memuat iklan…</div>:items.length===0?<div className="p-8 text-center"><b>Belum ada iklan.</b><p className="text-sm text-gray-500 mt-1">Mulai dengan memasang iklan pertama.</p><Link href="/sell" className="btn btn-primary mt-4">Pasang iklan</Link></div>:items.map((x:any)=><div className="p-5 flex items-center justify-between gap-4 border-b last:border-0" key={x.id}><div className="min-w-0"><b className="line-clamp-2">{x.title}</b><p className="text-xs text-gray-400 mt-1">{rupiah(x.price)} · {x.city} · {x.condition}</p><p className="text-xs mt-1">{x.status==='active'?<span className="text-green-700 font-bold">Aktif{x.is_pro_listing?' · Pro':!x.is_pro_listing&&x.expires_at?` · berakhir ${new Date(x.expires_at).toLocaleDateString('id-ID')}`:''}</span>:<span className="text-gray-500 font-bold">{x.status==='expired'?'Berakhir':'Tidak aktif'}</span>}</p></div><div className="flex shrink-0 gap-2">{x.status==='active'&&<Link href={`/listing/${x.id}`} className="btn border text-sm">Lihat</Link>}{x.status==='expired'&&<button type="button" disabled={busy===x.id} onClick={()=>reup(x.id)} className="btn btn-light text-sm"><RefreshCw className="w-4 h-4"/>{busy===x.id?'Memproses…':'Re-up'}</button>}</div></div>)}</div>
 <div className="card mt-6 overflow-hidden"><div className="p-5 border-b font-black flex items-center justify-between"><span>Penawaran masuk</span><span className="text-xs text-gray-400">{offers.length} total</span></div>{offers.length===0?<div className="p-6 text-sm text-gray-500">Belum ada penawaran.</div>:offers.slice(0,10).map((o:any)=><div className="p-5 border-b last:border-0 flex justify-between gap-4" key={o.id}><div><b>{o.listings?.title||'Iklan'}</b><p className="text-sm text-gray-500 mt-1">Penawaran {rupiah(o.amount)}</p></div><span className="pill">{o.status}</span></div>)}</div>
 <div className="card mt-6 p-5 flex gap-3"><ShieldCheck className="text-green-600 shrink-0"/><div><b>{profile?.seller_type==='pro'?'Pro Seller aktif':'Profil seller'}</b><p className="text-sm text-gray-500 mt-1">{profile?.seller_type==='pro'?'Status Pro membuat iklan tidak mengikuti masa tayang reguler.':'Lengkapi profil seller dan verifikasi sesuai proses Lumagada untuk membangun kepercayaan pembeli.'}</p><p className="text-xs text-gray-400 mt-2">{profile?.phone||user?.email}</p></div></div></main>;
}
