import {NextResponse} from 'next/server';
import {createClient} from '@/lib/supabase/server';
import {isRestrictedListing,restrictedServiceMessage} from '@/lib/policy';
import {boundedString,isUuid,rateLimit,rateLimitedResponse} from '@/lib/security';

export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){
 const guard=rateLimit(request,'listing:get',180,60_000);if(!guard.allowed)return rateLimitedResponse(guard.retryAfter);
 const {id}=await params;if(!isUuid(id))return NextResponse.json({error:'ID iklan tidak valid.'},{status:400});
 const supabase=await createClient();const {data,error}=await supabase.from('listings').select('id,title,description,price,condition,city,district,latitude,longitude,contact_phone,status,urgent,is_pro_listing,accepts_offers,expires_at,created_at,updated_at,listing_images(id,url,sort_order),seller_id,categories(name,slug)').eq('id',id).maybeSingle();if(error)return NextResponse.json({error:'Gagal mengambil iklan.'},{status:400,headers:{'cache-control':'no-store'}});if(!data)return NextResponse.json({error:'Iklan tidak ditemukan.'},{status:404});return NextResponse.json({data:{...data,category:(data as any).categories?.name||'Lainnya'}},{headers:{'cache-control':'no-store'}})
}

export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){
 const guard=rateLimit(request,'listing:patch',30,10*60_000);if(!guard.allowed)return rateLimitedResponse(guard.retryAfter);
 const {id}=await params;if(!isUuid(id))return NextResponse.json({error:'ID iklan tidak valid.'},{status:400});const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Login diperlukan.'},{status:401});
 const body=await request.json().catch(()=>null);if(!body||typeof body!=='object')return NextResponse.json({error:'JSON tidak valid.'},{status:400});if(body.action==='reup'){const {data,error}=await supabase.rpc('reup_listing',{p_listing_id:id});if(error)return NextResponse.json({error:'Iklan tidak dapat di-re-up.'},{status:400});if(!data)return NextResponse.json({error:'Iklan tidak dapat di-re-up.'},{status:422});return NextResponse.json({data},{headers:{'cache-control':'no-store'}})}
 const allowed=['title','description','price','city','district','latitude','longitude','contact_phone','accepts_offers','urgent'];const patch:any={};for(const key of allowed)if(key in body)patch[key]=body[key];
 if('title' in patch)patch.title=boundedString(patch.title,120);if('description' in patch)patch.description=boundedString(patch.description,5000);if('city' in patch)patch.city=boundedString(patch.city,100);if('district' in patch)patch.district=boundedString(patch.district,100);if('contact_phone' in patch)patch.contact_phone=boundedString(patch.contact_phone,30);if('price' in patch){patch.price=Number(patch.price);if(!Number.isInteger(patch.price)||patch.price<0||patch.price>9_000_000_000_000)return NextResponse.json({error:'Harga tidak valid.'},{status:422})}if('latitude' in patch){patch.latitude=Number(patch.latitude);if(!Number.isFinite(patch.latitude)||patch.latitude<-90||patch.latitude>90)return NextResponse.json({error:'Latitude tidak valid.'},{status:422})}if('longitude' in patch){patch.longitude=Number(patch.longitude);if(!Number.isFinite(patch.longitude)||patch.longitude<-180||patch.longitude>180)return NextResponse.json({error:'Longitude tidak valid.'},{status:422})}if('accepts_offers' in patch&&typeof patch.accepts_offers!=='boolean')return NextResponse.json({error:'Pilihan penawaran tidak valid.'},{status:422});if('urgent' in patch&&typeof patch.urgent!=='boolean')return NextResponse.json({error:'Status urgent tidak valid.'},{status:422});if('contact_phone' in patch&&patch.contact_phone.replace(/\D/g,'').length<10)return NextResponse.json({error:'Nomor HP/WhatsApp tidak valid.'},{status:422});
 if(Object.keys(patch).length===0)return NextResponse.json({error:'Tidak ada perubahan.'},{status:422});const current=await supabase.from('listings').select('title,description,condition').eq('id',id).eq('seller_id',user.id).maybeSingle();if(current.error||!current.data)return NextResponse.json({error:'Iklan tidak ditemukan.'},{status:404});if(isRestrictedListing({title:patch.title??current.data.title,description:patch.description??current.data.description,condition:current.data.condition}))return NextResponse.json({error:restrictedServiceMessage},{status:422});if(current.data.condition==='Lowongan')patch.accepts_offers=false;
 const {data,error}=await supabase.from('listings').update(patch).eq('id',id).eq('seller_id',user.id).select('id,expires_at,status,accepts_offers').maybeSingle();if(error)return NextResponse.json({error:'Iklan gagal diperbarui.'},{status:400});if(!data)return NextResponse.json({error:'Iklan tidak ditemukan.'},{status:404});return NextResponse.json({data},{headers:{'cache-control':'no-store'}})
}

export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){const guard=rateLimit(request,'listing:delete',20,10*60_000);if(!guard.allowed)return rateLimitedResponse(guard.retryAfter);const {id}=await params;if(!isUuid(id))return NextResponse.json({error:'ID iklan tidak valid.'},{status:400});const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Login diperlukan.'},{status:401});const {data,error}=await supabase.from('listings').delete().eq('id',id).eq('seller_id',user.id).select('id').maybeSingle();if(error)return NextResponse.json({error:'Iklan gagal dihapus.'},{status:400});if(!data)return NextResponse.json({error:'Iklan tidak ditemukan.'},{status:404});return NextResponse.json({data},{headers:{'cache-control':'no-store'}})}
